# Discussion and Conclusion

## Discussion


As discussed in the introduction section, there were five different possible hypotheses that we were able to come up with - one null hypothesis and four alternative hypotheses. Again, I will repeat all five of them below.

  1. A null result is found - the leaders and non-leaders do not change in significantly different ways.
  2. Leaders move to be more conservative, or right-leaning, when compared to non-leaders.
  3. Leaders move to be more liberal, or left-leaning, when compared to non-leaders.
  4. Leaders move to be more moderate, or centrist, when compared to non-leaders.
  5. Leaders move to be more extreme when compared to non-leaders.
  
Luckily I need not pick only one hypothesis above to describe the phenomena observed because three of the hypotheses seemed to be correct, depending on the circumstance.

Firstly, the null hypothesis seems to be correct in the vast majority of situations. While leadership can seem like an important identifier from the outside, it would make sense that they primarily follow or lead their party\footnote{It is impossible to know which direction the causality would go in from this analysis.} in such a way that their ideologies do not drastically change when compared with the mean change of the party. 

The null hypothesis might also have been found for a number of reasons related to the statistical analysis. For example the controls that I used could have also factored in a lot of the leadership variable outside of its specific predictor. This would be problematic for my results as I would be unable to find significance despite the actual leadership position having an effect on the legislator's ideology. A stronger understanding of statistics might allow a researcher to better tease out the significance of leadership on a legislator's ideology. Despite all of this however, it would not seem completely off-base for a null result to be found here. Perhaps party leaders are not unlike the rest of their caucus and they might just shift along with the rest of their legislators.


Secondly, the Democrats seemed to be explained well by the third and fifth hypotheses above, that leaders become more liberal or extreme when compared to non-leaders. There are a number of reasons why this could take place. Perhaps one of the most largest reasons I see being the case is that one of the largest threats for these leaders is that they are receiving a large amount of media attention and may attract a primary opponent. Leaders in both the Senate, and especially in the House because of the frequent elections, are often in seats that have a non-competitive general election. This can often mean that during the primary election that the incumbent may be challenged by a member of his own party, and this challenge will often come from the left. This would encourage the current leaders in Congress to shift farther towards the left in order to prevent an opponent from appearing or, if they do appear, from successfully challenging them for their seat. This again follows from @Mayhew2004 where the leaders are primarily focused on reelection.

This would also seem to make sense in the context of the ideology of the leaders that are elected by their fellow Members of Congress to lead their party. To reiterate, these leaders are not often middlemen, and instead are closer to their party's extremes than would be expected [@May1973; @Clausen1987; @Grofman2002; @Jessee2010].

Finally, the results were more significant for the Democrats during the New Deal era, or from 1933 to 1972, a period when the Democrats were in power in the House for a significant period of time, with only four years during this entire period with a Republican Speaker.\footnote{This occurred in the 80th and 83rd Congress, from 1947-1948 and 1953-1954, respectively. Joe Martin, a Representative from Massachusetts, was Speaker during this time.} While the literature review does not suggest why this period might be one of a greater shift towards the left by Democratic leaders there are possible reasons for this difference. It could be that as the party was feeling more comfortable in its position in the House the voters and other legislators wanted to see the party move farther towards the left. To understand why, imagine if party members were to always vote along party lines. You would have little incentive to move father towards the center once you had a majority of the seats in your chamber. As you keep gaining seats you gain a larger margin in the chamber. But if you pass a bill with 70% of the chamber it passes just the same as a bill that passes with 51% of support. So during this time of large Democratic margins and a sense of security of their leadership, the Democrats may have wanted more liberal policy to be passed. This would encourage the leaders to perhaps become more liberal than they otherwise would be.





## Conclusion

Overall it seems as if leadership positions can affect the ideology of a member in Congress, but that it is not always significant and when it is the degree to which it moves the Member of Congress can be small. Republicans were more likely to find null results, perhaps due to the long periods in which the party was out of power or due to a different attitude around leadership within the party. Democrats were more likely to have a leadership position affect their overall ideology, but the results were often small. The one time when the results seemed quite significant in their effect on the leader was during the New Deal system in Congress, from 1933 to 1972. This could have been due to the stronger party that existed at the time, and the pressure that a more liberal wing a larger party might put on the leaders of that party. 

This study was important because while information exists about how ideology matters when Members of Congress are elected to their leadership positions, the research had ended there. So while we might have been able to predict that John Boehner and Paul Ryan had ideologies that made them both reasonable choices for Speaker, the research did not yet speak to how their ideology might change when they obtained their position. This is an integral question as leaders have a large amount of power when compared to legislators that do not sit in leadership roles. 

These results found are far from the final word on the subject; they are actually the first. Subsequent analyses of this data could look at non-parametric approaches to try to better explain the variation in the data. More control variables could be added in order to better assess significance of the leadership predictor. For example, an age variable, or time spent in Congress variable, might have elicited some interesting results. More work could be done to examine the differences between the Republicans and Democrats - perhaps some case studies on how specific leaders changed their ideologies might be informative to the theory and story underlying the main question of this paper. Breaking down the data based on the type of leader that they are could also be useful. Bringing this research into committee leadership could also prove useful but would require a significant amount of additional coding to be done.

Overall, this paper has looked to narrow the gap of knowledge that exists around ideology and congressional leaders after they take their positions in their respective chambers. This study is imperfect and offers as many new questions as it strives to answer. Despite this, the information found on House Democrats during the New Deal system seems to be particularly robust. Research could be expanded in many areas, in particular it would be interesting to see if a researcher could try to establish an understanding of causality throughout different Congresses of whether the leaders are picking the ideology of the party or the party is encouraging the leaders to follow. This could help the burgeoning field of polarization research that surrounds the study of ideology in American politics currently. 

