# Methodology

```{r echo=F, message=F, warning=F}
library(ggplot2)
library(dplyr)

setwd("~/Insync/thesis/")

d <- read.csv("~/Insync/thesis/data/SenateData002.csv")
d <- d[,c("Cong.","ICPSR", "State.Code", "State", "Party", "Name", "X1st.Dim.", "X2nd.Dim.", "Role")]

d <- dplyr::rename(d, cong = Cong., 
                   icpsr = ICPSR,
                   statecode = State.Code,
                   state = State, 
                   party = Party,
                   name = Name, 
                   ideo = X1st.Dim., 
                   x2 = X2nd.Dim.,
                   role = Role)
start_cong <- 62

d1 <- d %>% # strips out 3rd party, before cong 60, make party variable D or R instead of 100 or 200
  mutate(leader = ifelse(role == "", NA, "Y")) %>%
  filter((party == 100 | party == 200) & cong >= start_cong) %>%
  mutate(party2 = ifelse(party == 100, "D","R")) %>%
  select(-party) %>%
  rename(party = party2)

#< Make party_cong_mean variable and ...
party_means <- data.frame(matrix(NA, nrow = 113, ncol = 0))
party_means$D     <- rep(NA, 113)
party_means$R     <- rep(NA, 113)
party_means$R_del <- rep(NA, 113)
party_means$D_del <- rep(NA, 113)

for(i in (start_cong+1):113) {
  party_means$D[i]  <- mean(dplyr::filter(d1, cong == i & party == "D")$ideo)
  party_means$R[i]  <- mean(dplyr::filter(d1, cong == i & party == "R")$ideo)
  party_means$D_del[i] <- party_means$D[i] - party_means$D[i-1]
  party_means$R_del[i] <- party_means$R[i] - party_means$R[i-1]
}

d2 <- dplyr::mutate(d1, party_cong_mean = ifelse(party=="D", 
                                                 party_means$D[cong], 
                                                 party_means$R[cong]))

d2 <- dplyr::mutate(d2, party_cong_mean_dif = ifelse(party=="D", 
                                                 party_means$D_del[cong], 
                                                 party_means$R_del[cong])) #>
```

I will use the `acf` function available in **R** to best estimate the number of years I should lag my data. It is assumed that I will see the highest correlation and covariance at the with a lag of `1`, meaning one congresional session behind.The correlation and covariance will be expected to slowly drop off. Once this `acf` function has been properly plotted I will be able to then move towards the fitting of a model to my data. To do that I will first seperate the data into two groups, Republicans and Democrats. Then again that data will be seperated into two groups, leaders and non-leaders. I will find the mean change of each party's ideology by congressional session within the `D-NOMINATE` dataset. Then I will compare the changes through each Congress of non-leaders to leaders within each party. This will allow me to see the differences in ideological change of one group versus the others.


