#Results

```{r source R, warning=F, message=F, echo=FALSE}
## REMOVE CHUNK LATER
source('~/thesis/rcode/plot_ideas.R', echo=FALSE)
```

Some statistically significant results are found in my most basic regression. These are the linear regressions computed across all the available congressional sessions that have complete leader data in both the House and the Senate, from the 67th Congress (1921-1923) to the recent 113th Congress (2013-2015). 

\begin{table}[h]
\centering
\caption{Summary of Models Across All Years, House and Senate}
\begin{tabular}{r|rrrr}
                       & Senate Ds & Senate Rs & House Ds & House Rs \\ \hline
(Intercept)            & 0.00489   & 0.00259   & 0.01131  & 0.00405  \\
cong\_ideo\_mean       & 0.51583   & 0.61344   & 0.73047  & 0.67749  \\
last\_cong\_ideo\_mean & -0.38112  & -0.50989  & -0.57483 & -0.53415 \\
last\_ideo             & 0.87467   & 0.87061   & 0.87636  & 0.85013  \\
leaderY                & \textbf{-0.01863}  & 0.01289   & -\textbf{0.03022} & -0.00417 \\
Adjusted R-Squared     & 0.802     & 0.781     & 0.781    & 0.824    \\
N                      & 2239      & 1817      & 11380    & 9270    
\end{tabular}
\end{table}


All of the control variables that were enlisted were found to be statistically signicant. These three variables were the idelogical mean of congress, the ideological mean of congress from the previous congressional session, and the congressperson's ideology from the previous congressional session. For all three of these variables across both parties in both the House and Senate the p-value was always less than 0.0001. It is clear that a legislator's current ideology would be affected by what their ideology was in the previous congressional session. While not as obvious, it also makes sense that you would need to understand the greater political environment that their party is in within their chamber. For example, if congresspeople as a whole were becoming more polarized at a rapid rate, as they are currently, you would expect a singular congressperson to be rapidly polarizing as well. Knowing how the party has changed from the previous Congress to the most recent one allows you to help control for this effect.

Across all of the years the leadership variable was statistically significant for the Senate Democrats and the House Democrats. The Senate Democrats noticed a small shift, approximately a 0.02 leftward shift on the D-NOMINATE scale, indicating that leaders become slightly more liberal across Congresses than their non-leader counterparts. The result was not significant at a confidence level of the normal 0.05, but with a p-value of 0.059 it would be recognized at a slighty higher confidence level.

A statistically significant shift was also noticed among the House Democrats. They had an even more statistically significant result, with a p-value of about 0.015



With the model I have created I think it is likely that the significance of leadership on ideology is underestimated. The change in leadership could have an effect on how the ideology of an entire caucus moves. Speaker Ryan right now is trying hard to make his ideology the ideology of the entire party, as he has pushed his agenda of "Confident America" [@Steinhauer2016]. Ryan is closer to the mean ideological scores of the Freedom Caucus, and one would imagine that a concerted effort to continue to elect leaders of more extreme ideologies might allow the rest of the party to move along with them towards their more extreme wings [@Enten2015].

Also the model might underestimate the importance of being a leader for a few another reasons. For example, leaders are a part of the data on the last congressional ideological mean and the current congressional ideological mean. Also leaders might have altered their early, pre-leader ideology because they expected or wanted to become leaders in the future. All of these could account for the differences among the significance of the leadership variable among the Democrats when compared to the Republicans. Perhaps Republicans were more likely to know they wanted to pursue leadership since they first entered office, or maybe they were more likely to shift along with their leaders, causing the entire mean of the party to move, possibly nullifing the effects of a leader's move.

.

.

.

.

.

.

There are five different outcomes that are possible with the above methodology.

  1. A null result is found - the leaders and non-leaders do not change in significantly different ways.
  2. Leaders move to be more conservative, or right-leaning, when compared to non-leaders.
  3. Leaders move to be more liberal, or left-leaning, when compared to non-leaders.
  4. Leaders move to be more moderate, or centrist, when compared to non-leaders.
  5. Leaders move to be more extreme when compared to non-leaders.
  
There are compelling reasons for many of these to be true. For outcome where the null result is found this could make sense if leaders and non-leaders have little reason to be different. One could imagine leaders becoming more conservative compared to non-leaders due to age of many of the leaders within Congress and the relation between ideology and age. They could become more moderate in order to fascilitate the dealmaking that must be done in Congress in order to get legislation passed. Or perhaps they would becoem more extreme in order to placate their more extreme bases, only choosing to delineate from them in the rarest of circumstances.