# Literature Review

## Congressional Leaders

Party leaders are hugely important in Congress. Perhaps their most important role is setting the legislative agenda in Congress [@Rohde1991 and @Sinclair1983]. By setting the agenda in arguably the most powerful branch of government, congressional leaders have extraordinary power over which bills are brought to a vote and eventually passed. They also have the power of being able to shift congressional actions away from an otherwise 
simple answer to a problem.^[For a recent example of this, see how in 2008 Harry Reid (D) then the majority leader of the Senate, was able to remove the possibility of a nuclear waste repository from being created at Yucca Mountain.] Leaders in Congress have large sway over the leaders who they can choose to fill the many roles below them. They are also the "brand image" of their party, especially when their party does not control the presidency. Understanding the ideology of leaders is important for a Congressional scholar to better understand why leaders act the way the do.

There has often been the question of whether or not congressional leaders are moderates in their party, near to their party's mean, or extremists. Moderates would often be effective legislators, as they would be able to propose more centrist policies that might apply to both political parties. Extremists might be selected due to their ability to placate the louder wings of both the Republican and Democratic parties. A political scientist or an economist might be quick to answer that a congressperson near the median voter in a political party has a strong theoretical reasoning for being chosen. 

Understanding what a median voter is as well as the median voter theorem is important for many quantitative approaches to the study of political ideology. A median voter is the voter in the middle of a group of voters measured among one or more dimensions.\footnote{As the number of dimensions increases however it can get more complicated to decide which voter is in fact the median voter. You have to properly scale each dimension to make sure some do not overpower others.} An table of voters is displayed below with their names and respective ideologies, picked from the actual numbers from the Nokken and Poole version of the D-NOMINATE dataset. These are the first dimensions scores, often categorized as ideology, with -1 being extreme liberalism and 1 being extreme conservatism. They are from the 113th Congress, the most recent Congressional session available in the dataset.


\begin{table}[]
\centering
\caption{Ideologies Presented for Median Voter Theorem Example}
\begin{tabular}{l|r}
Name      & Ideology \\ \hline
Warren    & -0.538   \\
Reid      & -0.422   \\
Wyden     & -0.381   \\
Warner    & -0.238   \\
Collins   & 0.061    \\
McCain    & 0.367    \\
Rubio     & 0.531    \\
McConnell & 0.568    \\
Cruz      & 0.754   
\end{tabular}
\end{table}

Here the median voter would be Senator Susan Collins, as her ideology, 0.061, puts her at the middle point, or the median, of the list of voters. The median voter theorem applies in majoritarian voting systems. The median voter, in this circumstance Senator Collins, will have their preferred outcome chosen by the voters in the system. A majoritarian voting system is when a vote is won when more than half of the votes are for a specific option. This is different than a plurality system, which just makes whichever has the most votes the winner, regardless of whether or not they have a majority of the votes. For example, if 40% voted for option A, 30% voted for option B, and 30% voted for option C then options A would be chosen under plurality rule, but not under majority rule. One of the options would need to be more than 50%. If say in a new vote option D got 50% of the vote that would not be enough to win in a majoritarian system as option E could also have 50% of the vote at the same time. 

To continue the discussion above, the reason why you might expect the congressperson elected to serve a leadership position to occupy the median space in the party is because in these elections the votes taken solely within the party.^[With the exception of the vote for Speaker in the House of Representatives, although that vote often ends up being made up entirely of the majority party's congresspersons voting in affirmation with the minority party avoiding casting a positive ballot.] The median voter theorem states that "a majority rule voting system will select the outcome most preferred by the median voter" [@Holcombe2006 115]. This builds off the assumption that there is only one dimension along which politics exists, for example, left to right or liberal to conservative. Is it also assumed that a voter will choose the option, or in this circumstance the politician, closest to their own ideal point along the singular dimension. In a majoritarian system this ideal median point will prevail, having more than 50\% of the vote in the final vote tallied. 

Studies have examined where leaders come from ideologically speaking. One has found, using the DW-NOMINATE scores of congressional leaders, that these leaders do in fact come from near the median of their party, with a tiny preference towards the slightly more extreme candidate, left-leaning for Democrats and right-leaning for Republicans. DW-NOMINATE scores place congresspersons on a single dimension from -1 to 1, with -1 being left-leaning and 1 being right-leaning. The numbers are found by taking the roll call votes over a single Congress and then placing the legislator's scores within the range of possible values. A senator like Ted Cruz would end up with a number close to 1^[In the 113th Congress his point was measured at 0.754.] whereas for senator like Elizabeth Warren you would see a point near to -1^[In the 113th Congress her point was measured at -0.538]. House Democrats were found to be on average -0.050 away from the median point whereas their leaders were on overage -0.097, slightly farther away but still close to the median. For Senate Democrats these numbers are 0.016 and -0.059 respectively, again the the leaders being slightly more extreme than the median but still being quite close to it. For the Republicans the results are similar, although in the other direction. In the House, for leaders the average distance away from the party median for leaders is 0.044 whereas for the rest of the House Republicans it is -0.025. For the Senate Republicans the numbers are 0.048 and 0.057, respectively.^[The Republicans in the Senate are the only group who elect leaders slightly more moderate on average than the party median in that chamber.] They find it "heartening to note that leaders--who some political observers argue have strong influence over agenda setting and lawmaking under certain conditions--are, on balance, fairly representative of their parties. If leaders came from the far extremes of the chambers...then policy might be even less reflective of the preferences of the median voter in the electorate" [@Jessee2010, see specifically 386]. @Jessee2010 also find that the winner of a congressional leadership race is not "ideologically distinctive" from the entire pool candidates [-@Jessee2010, 361].

This evidence found in @Jessee2010 looked to revise earlier studies on the subject. @Harris2008 looked at the old "Austin-Boston" alliance that encourage the selection of middlemen in the Democratic party, and also examine the changes within the Republican party leadership as well. Surprised by the election of the relatively extreme Pelosi to the Speakership, the two authors felt the need to revisit the question of whether the median voter theorem still held.^[While the middle*men* theory could still hold, the middle*person* theory was in doubt.] Using the same dataset as @Jessee2010, they came to a new conclusion, that perhaps more partisan leaders were need as political polarization increased. Seeing the role switch from a place for compromise during a "bargaining era and bipartisan Congress" to a new bully pulpit, often active in the media and courting donors, middlepersons seemed to no longer be the most appropriate leaders of their party on the national stage of Congress [@Harris2008 54]. Their final hypothesis is that as partisan divisions increase it will exacerbate the extremism of congressional leaders.

Older research is more theoretical and is less likely to use datasets, like the many NOMINATE datasets available. In @May1973 leaders are suggested to be more extreme than the rest of their party when ideology is strongly important, which may connect well to the modern era. Studies of both British and Norwegian legislative systems cast doubt on May's concept, the law of curvilinear disparity. The middleman theory is further promoted by @Clausen1987, who finds the best support for the theory in the House and then best within the Democratic party, which had at the time been the majority power for 32 years. Quickly stated, they claim that "leaders are chosen who are...dedicated to represent and prosecute the party position" [@Clausen1987 261]. More studies find evidence that leaders are more extreme than the median voter theorem would suggest, as Grofman, Koetzle, and McGann find that Democratic leaders are to the left of the median of their party and Republican leaders are to the right of the median of their party (@Grofman2002).

## DW-NOMINATE

Keith Poole's and Howard Rosenthal's previous work about congressional ideology is the backbone of this study. they have constructed a way to fit members of Congress across a unidimensional metric that measures primarily ideology. Their typical dataset measures a single "ideal point" for each congressperson throughout their career and is able to plot them against other members of Congress throughout its existence. There are alternative versions of their dataset that also exist, and I use the Nokken and Poole version, which allows members to shift their ideology throughout different sessions of Congress [@Nokken2004]. There is often a clamoring by many for the structure of Congress to be displayed in multiple different dimensions, sometimes even one dimension for every issue available. More often however there is a request for a second dimension that allows not just a conservative versus liberal axis but instead a socially liberal versus socially conservative axis and a fiscally liberal versus fiscally conservative axis. While at times a second axis is useful, and in the most recent session of Congress can be viewed as a measure of establishment versus non-establishment leanings, Poole and Rosenthal as well as those who have use their datasets in the past primarily look to create their models solely from this one dimension due to its explanatory power [@Poole2007 21]. Part of the reason why complicated legislators are able to represented along a single metric is due to the prevalence of logrolling or vote trading [@Poole2007 17]. The primary dimension is not solely concerned with political party however, it also strongly relates to issues of economic redistribution [@Poole2007 70].

Looking ahead to how the legislators, specifically the leaders, might change within my own study is evidence that "essentially all movement is captured by simple linear movement" along the single explanatory dimension, which suggests that more complicated ideological flip flops are rare within Congress [@Poole2007 29].

Poole and Rosenthal are able to look at the patterns of how ideology has changed in the history of Congress. I will solely be looking at post-WW2 data as that is when congressional leadership started becoming truly strong in both the House and Senate.^[Before that it was sometimes non-existent, especially in the smaller Senate, where leadership was not needed as much to organize the many members of each party.] They note that "[t]he period from the late New Deal until the mid-1970s saw the development of the only genuine three-political-party system in American history. The southern and northern Democrats may have joined together to organize the House and Senate but they were widely separated on the second dimension. This dimension picked up conflict over civil rights" [@Poole2007 54]. During this time there was a conservative coalition between the southern Democrats and most Republicans that was in conflict with the northern Democrats as well a a few northern Republicans [@Poole2007 54-56]. It is unfortunate that this sole time of a three-political-party stem exists during the data that I plan to use, but this may make my results stronger in less turbulent times. By the "mid-to-late 1970s the party-line voting returned to a more [unidimensional] pattern" [@Poole2007 57]. This was due to the passage of civil rights legislation that either revolved conflicts within the parties or caused legislators to switch from one party to another Throughout the rest of congressional history the single dimension remains but what the dimensions refers to evolves slowly. Within each individual Congress it is easy to see the majority of conflicts along a single dimension [@MacDonald1987].

Something that should help my analysis is the movement towards a more "unidimesional politics" in the most recent sessions of Congress. The ideological overlap along this single dimension between the parties is essentially gone. The last Congress in which there was an overlap in the Senate was the 109th, which ended in early 2007. The second dimension has lost much of it's explanatory power towards party since the 104th Congress, which began in 1995. Poole and Rosenthal say that "the modern Congress is truly unidimensional" in 2005, which was before the even greater polarization that began then and continues to move the two parties father apart [@Poole2007 55]. The first dimension, while often referred to as "ideology," can be though of in a few different ways. It could be that the dimension is "thought of as ranging from strong loyalty to one party" to a strong dislike of the policies of another party; this can often explain the placement of many independent or otherwise third-party congressmen^[As every third-party Representative or Senator has been a man.] existing seemingly deep within another party [@Poole2007 55].

Poole and Rosenthal put dimensional and roll call voting agendas well in the following quote: "In a nutshell, the roll cal voting agenda of Congress is always a cornucopia of diverse issues, even if many issues are screened from the agenda. This diversity notwithstanding, to the extent that spatial models are useful in describing the roll call voting data, only low-dimensional models are needed" [-@Poole2007 69].







