# Introduction {.unnumbered}

When Boehner announced his retirement from his role as House Speaker on September 25th, 2015 pundits thought they believed they knew who was going to be the next Speaker. They placed their bets on Kevin McCarthy, the House Majority Leader and a Representative from California, to move up to the position of House Speaker, as it often is the tradition to do. However there were fractures in the Republican party that were unable to mended with McCarthy as Speaker, and after a period of wooing, the 2012 Republican Vice Presidential nominee and Ways and Means Committee Chairman Paul Ryan, a Representative from Wisconsin, was elected to become the new leader of the House. He was less establishment and more right wing than Speaker Boehner, who himself was less establishment minded and more conservative than Majority Leader McCarthy. Paul Ryan was significantly closer to the mean ideology of the other members of the House Freedom Caucus. This quite likely made his ascension to Speaker a less controversial pick than McCarthy would have been [@Enten2015]. But now that Paul Ryan is Speaker, how do we expect his ideology to change now that the he holds arguably the second most powerful position in American politics after the Presidency itself?

This question has so far gone unexplored in the study of political ideology. How do leaders move ideologically compared to a non-leader Member of Congress? Past research has looked at how leaders are chosen from their party to become leaders, but the research typically has ended there. This paper's analytical tools are primarily quantitative. Using measures of ideology from a `NOMINATE` dataset models are fit based on party and leadership status. The leaders are then compared to the non-leaders on how their ideology changes compared to the mean ideology of Congress at the time and the models are assessed for statistical significance. There are five possible outcomes. They are:

  1. A null result is found - the leaders and non-leaders do not change in significantly different ways.
  2. Leaders move to be more conservative, or right-leaning, when compared to non-leaders.
  3. Leaders move to be more liberal, or left-leaning, when compared to non-leaders.
  4. Leaders move to be more moderate, or centrist, when compared to non-leaders.
  5. Leaders move to be more extreme when compared to non-leaders.

It seems like the null result should be expected the most due to the large number of other factors that could cause changes in a legislator's ideology and just due to trends in the literature. Null results are common, but often not reported. That being said there are good reasons for all the hypotheses above. For Hypothesis 2 it could make the most sense as leaders are getting older the people often become more conservative the older they get. Hypothesis 3 could be explained by a country that has moved to the left on a number of issues, in particular social issues, in the last generation. Hypothesis 4 would make sense in the context of a leader's desire to form compromise between the two parties that are dominant in the American Political system. Finally, Hypothesis 5 would make sense due to the number of loud forces that exist on both the Democratic and Republican sides that have pushed polarization in Congress farther than it has gone in the the past century. These hypotheses are tested later on within this paper.

The paper begins with a literature review to try to comprehend the previous research done on the subject of ideology and Congressional leadership as it applies to this paper. Then the dataset is described in more detail and the methods to be used in the analysis are presented. Next the results are displayed. A discussion of the results follows, and the paper ends with a conclusion of the results found in the study and a look towards future research in this field.

